// react/src/App.tsx
import reactLogo from './assets/react.svg'
import './App.css'
import {Qtheme, Theme} from '@quak.lib/qtheme';
import {darkTheme, lightTheme} from './themes';

function App() {
    let isDarkMode = true
    const setLightTheme = () => {
        Qtheme.setTheme(lightTheme)
        const { lightButton, darkButton } = getLightDarkButtons()
        darkButton!.classList.remove('text-primary')
        lightButton!.classList.add('text-primary')
    }
    const setDarkTheme = () => {
        Qtheme.setTheme(darkTheme)
        const { lightButton, darkButton } = getLightDarkButtons()
        lightButton!.classList.remove('text-primary')
        darkButton!.classList.add('text-primary')
    }

    const savedTheme: Theme | null = Qtheme.getTheme()
    if (savedTheme) {
        Qtheme.setTheme(savedTheme)
        isDarkMode = savedTheme.name === 'dark'
    } else {
        Qtheme.setTheme(darkTheme)
    }

    const lightButtonCss = `text-color ${!isDarkMode ? 'text-primary' : ''}`
    const darkButtonCss = `text-color ${isDarkMode ? 'text-primary' : ''}`

    return (
        <div className="App">
            <div>
                <a href="https://reactjs.org" target="_blank">
                    <img src={reactLogo} className="logo react" alt="React logo"/>
                </a>
            </div>

            <h1 className="text-primary">Hello world!</h1>
            <p className="text-color">This is regular text color</p>

            <hr/>

            <button onClick={() => setLightTheme()} id="light_btn" className={lightButtonCss}>Set light theme</button>
            <button onClick={() => setDarkTheme()} id="dark_btn" className={darkButtonCss}>Set dark theme</button>
        </div>
    )
}

export default App

function getLightDarkButtons() {
    const lightButton = document.getElementById('light_btn')
    const darkButton = document.getElementById('dark_btn')
    return {lightButton, darkButton}
}

// angular/src/app/app.component.ts
import {Component} from '@angular/core';
import {Qtheme} from '@quak.lib/qtheme';
import {darkTheme, lightTheme} from '../themes';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular';
  isDarkMode = true;

  constructor() {
    Qtheme.setTheme(darkTheme);
  }

  setLightTheme(): void {
    Qtheme.setTheme(lightTheme);
    this.isDarkMode = false;
  }

  setDarkTheme(): void {
    Qtheme.setTheme(darkTheme);
    this.isDarkMode = true;
  }
}

<div id="app">
  <div>
    <a href="https://angular.io/" target="_blank">
      <img
        class="logo angular"
        width="100"
        alt="Angular Logo"
        src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
      />
    </a>
  </div>


  <h1 class="text-primary">Hello world!</h1>
  <p class="text-color">This is regular text color</p>

  <hr/>

  <button (click)="setLightTheme()" [ngClass]="{'text-primary': !isDarkMode}" class="text-color">Set light theme</button>
  <button (click)="setDarkTheme()" [ngClass]="{'text-primary': isDarkMode}" class="text-color">Set dark theme</button>

</div>
